language: python

python:
    - 3.3
    - 3.4

install:
    - pip install -r requirements.txt
    - pip install -U pytest
    - pip install coveralls

script:
    - coverage run --source=serename -m py.test

after_success:
    - coveralls

notifications:
    email: false
